---
author: Santiago G. Rios
title: Analista de Conducta Experimental
tagline: 
  field1: Santiago Garcia Rios
  field2: Analista de Conducta
  field3: Neurobiólogo
  colored: santiagoboo99@gmail.com
  field5: Ciudad de México, México
format:
  modern-cv-pdf: default
cvfooter:
  left: "https://santi-rios.github.io/"
  right: "github.com/santi-rios"
cvcolor: 142c63 #without `#`
bgcolor: 616161
cvfont: raleway #texlive fonts like raleway,fetamont,gillius,comfortaa
cvmeta:
  - title: Estado
    text: "Cursando Maestría en Neurobiología y Conducta en la Universidad Nacional Autónoma de México (UNAM)"
  - title: Habilidades
    text: R, Bash, Python, Docker, \LaTeX, Shiny, JavaScript, HTML, CSS, Markdown, SQL, webAssembly
  - title: Idiomas
    text: "Inglés (C2), Español (Nativo)"
execute:
  echo: false
---

```{r}
#| label: cvevents

cvevents <- function(tbl, when, what, where, para1,para2) {

    command_start <- "\\cvevent"

    res <- paste0(
        command_start, "{", tbl[[when]], "}", 
        "{", tbl[[what]], "}",
        "{", tbl[[where]], "}",
        "{", tbl[[para1]], "}",
        "{", tbl[[para2]], "}"
        )

    cat(res, sep = "\n")
}
```

# Educación

```{r}
#| label: education
#| output: asis

tibble::tribble(
    ~grado, ~universidad, ~ubicacion, ~fechas, ~detalle1, ~detalle2,
    "Maestría en Ciencias en Neurobiología y Conducta", 
    "Universidad Nacional Autónoma de México", 
    "UNAM, Ciudad de México", 
    "2022 - 2025", 
    "Tesis: Caracterización de los efectos de la fluoxetina en la conducta y el aprendizaje espacial en un modelo de estrés leve en ratones", 
    "Desarrollé e implementé nuevos métodos para evaluar conductas similares a la depresión y cognición usando R via WebAssembly en computación serverless",
    
    "Licenciatura en Biología", 
    "Universidad Nacional Autónoma de México", 
    "UNAM, Ciudad de México", 
    "2019 - 2022", 
    "Tesis: Efectos de la estimulación magnética transcraneal en la expresión de receptores cannabinoides en un modelo de lesión cerebral en ratas", 
    "Implementé técnicas de laboratorio en inmunología, genética y conducta"
) |>
    cvevents(when = "fechas", what = "grado", where = "ubicacion", para1 = "detalle1", para2 = "detalle2")


```

# Publicaciones y Trabajos Destacados

```{r}
#| label: experience
#| output: asis

tibble::tribble(
    ~grado, ~universidad, ~ubicacion, ~fechas, ~detalle1, ~detalle2,
    "Desarrollo de Aplicación Shiny para explorar el artículo: China's rise in the chemical space and the decline of US influence", 
    "Esta aplicación proporciona una exploración de las tendencias globales en investigación química. Construida para profundidad técnica y experiencia de usuario.",
    "Colaboración internacional",
    "2025",
    "Disponible en $http://64.23.171.120:3838/users/bermudez/minimal_app/$ ",
    "DOI $https://doi.org/10.26434/chemrxiv-2025-d2zc8$",
    
    "Plantilla de Quarto-LAtex \"todo en uno\" para tesis de licenciatura, maestría o doctorado",
    "La plantilla utiliza docker para instalar y configurar todos los paquetes necesarios para compilar la tesis SIN necesidad de instalar nada en tu computadora (más allá de docker).",
    "Desarrollo de Software",
    "2025",
    "Disponible en: $https://github.com/santi-rios/UNAM-Tesis-TodoEnUno$",
    "Repositorio: $https://github.com/santi-rios/UNAM-Tesis-TodoEnUno$",
    
    "IA, cognición humana y juegos de estrategia",
    "En 1912, el inventor español Leonardo Torres Quevedo construyó una máquina autómata capaz de jugar ajedrez y vencer a sus contrincantes de carne y hueso, conocida como El ajedrecista...",
    "Revista Nexos",
    "2025",
    "Disponible en $https://ciencia.nexos.com.mx/ia-cognicion-humana-y-juegos-de-estrategia/$",
    "Más artículos de divulgación disponible en $https://santi-rios.github.io/publications/$",
    
    "Desarrollo de aplicación serverless para cálculo de entropia en el Laberinto Acuático de Morris",
    "Aplicación desarrollada para el análisis de conductas en el Laberinto Acuático de Morris en R y Shiny con tecnología serverless para el cálculo de entropía de Shannon.",
    "Proyecto de Maestría",
    "2024",
    "App alojada en github serverless disponible en $https://santi-rios.github.io/maestria_app_water_maze/$",
    "repositorio $github.com/santi-rios/wm_app$"
    
    # "2021",
    # "Degenerados, ¿los enemigos de la sociedad?",
    # "https://ciencia.nexos.com.mx/degenerados-los-enemigos-de-la-sociedad/",
    # "Explora cómo la 'teoría de la degeneración' influyó en la medicina, psiquiatría y biología evolutiva.",
    
    # "2021",
    # "Alzheimer: últimas noticias",
    # "https://discapacidades.nexos.com.mx/alzheimer-ultimas-noticias/",
    # "Reflexión sobre la conciencia del Yo y el impacto de Alzheimer en la identidad personal.",
    
    # "2021",
    # "Antidepresivos: serendipia y efectos inesperados",
    # "https://discapacidades.nexos.com.mx/antidepresivos-serendipia-y-efectos-inesperados/",
    # "Historia de los primeros antidepresivos derivados de compuestos bélicos reutilizados.",
    
    # "2022",
    # "Un repaso por la esquizofrenia y sus tratamientos",
    # "https://discapacidades.nexos.com.mx/un-repaso-por-la-esquizofrenia-y-sus-tratamientos/",
    # "Panorama histórico y actual de los tratamientos para la esquizofrenia en México."
) |>
    cvevents(when = "fechas", what = "grado", where = "ubicacion", para1 = "detalle1", para2 = "detalle2")

```